### ISSUE TITLE
Error executing manual mesh with Euclid probe, using profile name with a space

### ISSUE THREAD

**Issue by etotheipi** [Rat-OS/RatOS-configuration#126]
### What happened

I tried to generate a mesh from the "Heightmap" menu after updating to a Euclid probe, and used the name "Euclid Mesh" which then threw an error that indicates the name is not being quoted properly:

Malformed command `'BED_MESH_CALIBRATE_ORIG PROFILE=Euclid Mesh'`

When I rerun with a name that has no space, it works fine.

### What did you expect to happen

I expected it to properly encapsulate the profile name with quotes so it doesn't treat the user-provided name as more than one argument.

### How to reproduce

Do the stowable-probes thing and then try to generate a mesh from the "HEIGHTMAP" menu using a name that has a space in it.

**Comment by miklschmidt** [comment]
Will be fixed once #137 is merged

**Comment by miklschmidt** [comment]
fixed a year ago, apparently forgot to close :D
