### ISSUE TITLE
Slow UI load times

### ISSUE THREAD

**Issue by jLynx** [Rat-OS/RatOS-configuration#144]
### What happened

When I load the webpage it takes around 8-20 seconds to load. (Validated on multiple high-end devices). After talking to the Mainsail guys, they said its a RatOS issue as it has to load all the config items before it renders.
![image](https://github.com/Rat-OS/RatOS-configuration/assets/4393979/a04641cc-10a2-4fb4-9b58-c2175b4d9cc8)

### What did you expect to happen

The page to load a lot faster than it currently does

### How to reproduce

Im not sure. Its a stock config. just with a lot of use time (438hours)

### Additional information

https://github.com/Rat-OS/RatOS-configuration/assets/4393979/61c7380c-8376-4ade-ab3c-a7b693c39aa6

https://github.com/Rat-OS/RatOS-configuration/assets/4393979/4aa5a27d-b621-418f-bfd6-3ccf810838ad

**Comment by jLynx** [comment]
Apparently it could be to do with the file history, so I have created this too https://github.com/mainsail-crew/mainsail/issues/1468

**Comment by miklschmidt** [comment]
I'd argue that loading stuff before it's needed is a rookie web development mistake.

**Comment by miklschmidt** [comment]
@jLynx i'm closing this as it's a mainsail performance issue. Feel free to reopen if you have any questions.

**Comment by jLynx** [comment]
Sounds good to me
