### ISSUE TITLE
Allow for configuration of inital_pins in menuconfig for firmwares

### ISSUE THREAD

**Issue by SirUli** [Rat-OS/RatOS-configuration#146]
### Is your feature request related to a problem? Please describe

I run a E3EZ together with the BTT Relay which means that i have to pull the PA9 to high on startup of the board to enable the PS_ON pin. When configuring that in klipper it is already too late and the relay has shutdown in the meantime (8 seconds to start is too low as a delay). As the pi is embedded on the board, everything is off by that time then.

When manually changing the config for the firmware to set the initial pin PA9 to high, the relay stays on. But with the next update this would be gone to my understanding.

### Describe the solution you'd like

Allow for a pre-configuration of the setting CONFIG_INITIAL_PINS of the firmware configuration.

### Describe alternatives you've considered

Dropping the auto-builder of RatOS and doing it manually.

**Comment by miklschmidt** [comment]
This will indeed be possible in a future release of the RatOS configurator as part of a bigger feature set, but it's not happening anytime soon unfortunately. The only option currently, like you already considered, is to flash it yourself (if you don't set the chip id in the firmware config, it won't be mapped by the associated RatOS udev rule and the RatOS configurator won't flash it, so you can manage it manually - just remember to set the `[mcu]` section's `serial` parameter yourself in your printer.cfg).
