### ISSUE TITLE
Manta M8P V2.0

### ISSUE THREAD

**Issue by trudeau87** [Rat-OS/RatOS-configuration#157]
### Is your feature request related to a problem? Please describe

No option for Manta M8P V2.0

### Describe the solution you'd like

Can this be added to the config of the RatOS?

**Comment by sergelhr** [comment]
> ### Is your feature request related to a problem? Please describe
> 
> No option for Manta M8P V2.0
> ### Describe the solution you'd like
> 
> Can this be added to the config of the RatOS?
> ### Describe alternatives you've considered
> 
> _No response_
> ### Additional information
> 
> _No response_

I'm using this board already see https://github.com/sergelhr/RatOS-configuration

**Comment by miklschmidt** [comment]
This is implemented in the `development` branch and will be published with 2.1

**Comment by LivioB74** [comment]
Sorry, if possible know when version 2.1 will be implemented ? 
I need to printing whith my new RatRig, the only printer that i have after death of my creality :(
Otherwise can i do to configure Klipper standard with correct profile for VCore3.1 500 using Manta M8P v2.0 & CB1 without using RatOS ?
I will preferred RatOS and all features but Standard Klipper can be ...
please, help me. Many Thanks !!

**Comment by miklschmidt** [comment]
@LivioB74 Unfortunately i can't give a specific date at this point, but we're getting close to public beta. There are some major features being developed and tested right now that need to be completed first. 

That said, if you can live with the update manager reporting "dirty" in the mainsail machine tab, you can just simply install RatOS 2.0, update all packages, then dump [this folder](https://github.com/Rat-OS/RatOS-configuration/tree/v2.x/boards/btt-manta-m8p) into `/home/pi/printer_data/config/RatOS/boards`. Then ssh into the pi and run the ratos update script:
```bash
ssh pi@ratos.local
sudo ./printer_data/config/RatOS/scripts/ratos-update.sh
```

And then go to the configurator to flash your Manta M8P v2.0. To use the board in printer.cfg, comment out the existing boards and add `[include RatOS/boards/btt-manta-m8p-20/config.cfg]`. Now your Manta M8P v2 works in RatOS v2.0. You just won't be able to update RatOS without resetting it and then you'd have to drop it back in again.

You'll have to download [the wiring diagram](https://github.com/Rat-OS/RatOS-configuration/blob/development/boards/btt-manta-m8p-20/wiring.drawio.svg)/[fan wiring diagram](https://github.com/Rat-OS/RatOS-configuration/blob/development/boards/btt-manta-m8p-20/fan-wiring.drawio.svg) and open them locally to view the images.

**Comment by LivioB74** [comment]
HI @miklschmidt !
Many Many Thanks !!!
Now i will try ... This way is the same that i try to do except for ratos-update ... and re flash manta ...
Good Work ! And thanks again ... I'm curious to know new features :-)

**Comment by LivioB74** [comment]
HI
To confirm if my steps are correct:

- Write img  RatOS 2.02 on sdcard
- Edit file system.cfg,ratos-wpa-supplicant, boardenv.txt on sd card
- insert SDcard into CB1 and stard printer
- ssh pi@ratos.local
- sudo apt update && upgrade -y
- scp -r \btt-manta-m8p-20 pi@ratos:/home/pi/printer_data/config/RatOS/boards
- sudo ./printer_data/config/RatOS/scripts/ratos-update.sh
- http://ratos.local
- compile firmware (script start shell in Console that compile all fw, right ?)
- install VCORE THREE CONFIG macro button from Installation menu

and it's all ...

but no succes ... not connecting  ....

some hints ?

**Comment by miklschmidt** [comment]
Not quite how it goes. You know [we have documentation](https://os.ratrig.com/docs/installation) for the setup process right? Just follow that. Before you go to boards (so after configuring wifi) update everything through mainsail/moonraker ( i'm not talking about the system packages), dump the folder in and run the ratos-update.sh script. Then proceed with the guide at `/configure`, and everything should be the same - except you have to add the board include to printer.cfg yourself at the end.

**Comment by LivioB74** [comment]
OK ! I  restart ... Thanks !

**Comment by LivioB74** [comment]
Sorry again, i have probally a little confusion ...
- under RatOS/config/boards i must create folder "btt-manta-m8p-20" ?
- after i must dump (content from you "this folder"  (https://github.com/Rat-OS/RatOS-configuration/tree/v2.x/boards/btt-manta-m8p) into boards or into btt-manta-m8p-20 ?
Please, must have patience ... i'm a donk :(
But in any case RatOS configurator give me this error : Error
Invalid board definition(s) in /home/pi/printer_data/config/RatOS/boards.
I find this procedure too easy foe me and i fault or too difficult and i fault again ... i dont understand where and whi ... or probally i make something wrong ... 
so i try again and again ...

**Comment by miklschmidt** [comment]
@LivioB74 No, that's the manta m8p v1 from the v2.x branch. You want this folder https://github.com/Rat-OS/RatOS-configuration/tree/development/boards/btt-manta-m8p-20

It's the same repository but a different branch, you're just replicating the files for that board in your local v2.x copy of the repository. Same folder name, same file contents.

It's complaining because you duplicated a board config (the manta m8p v1).

**Comment by IridianZore** [comment]
Hi,
Do you have any update when the release of 2.1 will be?

**Comment by miklschmidt** [comment]
@IridianZore it will coincide with the release of the V-Core 4 :)

**Comment by IridianZore** [comment]
I copied the files on the above link to the boards file of the OS.
Then I started RatOS Setup Wizard. 
Unfortunately I always get the same error.
Invalid board definition(s) in /home/pi/printer_data/config/RatOS/boards.

Can you help me get my manta m8p v2 with cb1 working.

**Comment by IridianZore** [comment]
> > ### Is your feature request related to a problem? Please describe
> > No option for Manta M8P V2.0
> > ### Describe the solution you'd like
> > Can this be added to the config of the RatOS?
> > ### Describe alternatives you've considered
> > _No response_
> > ### Additional information
> > _No response_
> 
> I'm using this board already see https://github.com/sergelhr/RatOS-configuration

Can you give me a workflow how to handle it.
I'm a newbe and don't have this deep knowledge....

**Comment by miklschmidt** [comment]
> I copied the files on the above link to the boards file of the OS. Then I started RatOS Setup Wizard. Unfortunately I always get the same error. Invalid board definition(s) in /home/pi/printer_data/config/RatOS/boards.
> 
> Can you help me get my manta m8p v2 with cb1 working.

Ah yes, i forgot serialPath is removed in 2.1.

try adding `"serialPath": "/dev/btt-manta-m8p-20",` after the first line (with the opening `{`) to `boards/btt-manta-m8p-20/board-definition.json`

**Comment by IridianZore** [comment]
you mean as below mention?
"dfu": {
		"serialPath": "/dev/btt-manta-m8p-20"
		"flashDevice": "0483:df11",
		"dfuBootImage": "dfubooting.png",
		"instructions": [
			"Make sure the board is powered on",
			"Press and hold the BOOT 0 button on the board.",
			"Press and release the RESET button on the board.",
			"Release the BOOT 0 button."
		],
		"hasBoot0Jumper": false
	},

**Comment by IridianZore** [comment]
![Screenshot 2024-04-08 002122](https://github.com/Rat-OS/RatOS-configuration/assets/145200529/7ba46a7f-3cd7-4ad6-8277-c6d5d946a099)

**Comment by miklschmidt** [comment]
> you mean as below mention? "dfu": { "serialPath": "/dev/btt-manta-m8p-20" "flashDevice": "0483:df11", "dfuBootImage": "dfubooting.png", "instructions": [ "Make sure the board is powered on", "Press and hold the BOOT 0 button on the board.", "Press and release the RESET button on the board.", "Release the BOOT 0 button." ], "hasBoot0Jumper": false },

No, and if that's the entire contents of your board-definition.json then you didn't copy the files or you edited and deleted some of the board definition file. It should be inserted here [below this line in the file](https://github.com/Rat-OS/RatOS-configuration/blob/development/boards/btt-manta-m8p-20/board-definition.json#L3).

**Comment by IridianZore** [comment]
I just picked out the part with the entry.
This is the complet fil
[board-definition.json](https://github.com/Rat-OS/RatOS-configuration/files/14899305/board-definition.json)

**Comment by miklschmidt** [comment]
> I just picked out the part with the entry. This is the complet fil [board-definition.json](https://github.com/Rat-OS/RatOS-configuration/files/14899305/board-definition.json)

Gotcha. Anyway, it should not go under "dfu", it needs to be at the top level, it also needs a comma at the end. This is what you want:
```json
{
	"$schema": "../board-definition.schema.json",
	"serialPath": "/dev/btt-manta-m8p-20",
	"name": "Manta M8P v2.0",
	"manufacturer": "BIGTREETECH",
	"id": "btt-manta-m8p-20",
	"firmwareBinaryName": "firmware-btt-manta-m8p-20.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"documentationLink": "https://os.ratrig.com/docs/boards/btt/manta-m8p-11",
	"fourPinFanConnectorCount": 2,
	"driverCount": 8,
	"driverVoltages": [24, 36, 48, 56],
	"dfu": {
		"flashDevice": "0483:df11",
		"dfuBootImage": "dfubooting.png",
		"instructions": [
			"Make sure the board is powered on",
			"Press and hold the BOOT 0 button on the board.",
			"Press and release the RESET button on the board.",
			"Release the BOOT 0 button."
		],
		"hasBoot0Jumper": false
	},
	"motorSlots": {
		"MOTOR1": {
			"title": "MOTOR 1",
			"enable_pin": "PC14",
			"step_pin": "PE6",
			"dir_pin": "PE5",
			"uart_pin": "PC13",
			"cs_pin": "PC13",
			"diag_pin": "PF4",
			"endstop_pin": "PF4",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"MOTOR2": {
			"title": "MOTOR 2",
			"enable_pin": "PE4",
			"step_pin": "PE2",
			"dir_pin": "PE1",
			"uart_pin": "PE3",
			"cs_pin": "PE3",
			"diag_pin": "PF3",
			"endstop_pin": "PF3",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"MOTOR3": {
			"title": "MOTOR 3",
			"enable_pin": "PE0",
			"step_pin": "PB8",
			"dir_pin": "PB7",
			"uart_pin": "PB9",
			"cs_pin": "PB9",
			"diag_pin": "PF2",
			"endstop_pin": "PF2",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"MOTOR4": {
			"title": "MOTOR 4",
			"enable_pin": "PB6",
			"step_pin": "PB4",
			"dir_pin": "PB3",
			"uart_pin": "PB5",
			"cs_pin": "PB5",
			"diag_pin": "PF1",
			"endstop_pin": "PF1",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"MOTOR5": {
			"title": "MOTOR 5",
			"enable_pin": "PG15",
			"step_pin": "PG13",
			"dir_pin": "PG12",
			"uart_pin": "PG14",
			"cs_pin": "PG14",
			"diag_pin": "PF0",
			"endstop_pin": "PF0",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"MOTOR6": {
			"title": "MOTOR 6",
			"enable_pin": "PG11",
			"step_pin": "PG9",
			"dir_pin": "PD7",
			"uart_pin": "PG10",
			"cs_pin": "PG10",
			"diag_pin": "PC15",
			"endstop_pin": "PC15",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"MOTOR7": {
			"title": "MOTOR 7",
			"enable_pin": "PD6",
			"step_pin": "PD4",
			"dir_pin": "PD3",
			"uart_pin": "PD5",
			"cs_pin": "PD5",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"MOTOR8": {
			"title": "MOTOR 8",
			"enable_pin": "PD2",
			"step_pin": "PC7",
			"dir_pin": "PC8",
			"uart_pin": "PC6",
			"cs_pin": "PC6",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		}
	},
	"ADXL345SPI": {
		"cs_pin": "PB12",
		"software": {
			"sclk": "PC10",
			"mosi": "PC12",
			"miso": "PC11"
		}
	},
	"stepperSPI": {
		"software": {
			"sclk": "PC10",
			"mosi": "PC12",
			"miso": "PC11"
		}	
	}
}
```

**Comment by IridianZore** [comment]
> -

YES! ;) It worked! Great job! Thank you so much!
![Screenshot 2024-04-08 074914](https://github.com/Rat-OS/RatOS-configuration/assets/145200529/56a8b372-6152-4b38-aeb8-bb32a806a4ef)

**Comment by aardvarkglory** [comment]
I followed this as mentioned above.  I am able to click on the M8P v2 board and it goes to the next page.  It gives me 2 options for flashing, DFU or Manual SD.  When I click on the button for DFU or Manual flash, the button itself quickly flashes and does nothing.  Is there anything I can do to make this feature work?

**Comment by sergelhr** [comment]
Hello did you try to flash the bootloader ?
https://github.com/bigtreetech/Manta-M8P/tree/master/V2.0/Firmware

**Comment by miklschmidt** [comment]
v2.1.0-RC1 has been released with native support.

**Comment by aardvarkglory** [comment]
> v2.1.0-RC1 has been released with native support.

Thanks and awesome work on 2.1.  Installed it and fixed this issue among other issues.  Thanks.
