### ISSUE TITLE
Duplicate configure screen entries for SKR 3 EZ

### ISSUE THREAD

**Issue by LongLiveCHIEF** [Rat-OS/RatOS-configuration#164]
### What happened

Looks like the v2.0 release was supposed to rename the `RatOS/boards/btt-skr-3-ez` configuration to `RatOS/boards/btt-skr-3-ez-h723` (see https://github.com/Rat-OS/RatOS-configuration/commit/526a9fbfa5805cd0952af48493109dc70fb533b2).

At some point though, it looks like the `RatOS/boards/btt-skr-3-ez` folder managed to sneak back in, and as a result there is a duplicate entry in the configure screen for `BIGTREETECH SKR 3 EZ H723`. 

One of these will cause udev rules to create a symlink for `btt-skr-3-ez`, and the other will cause udev to create a symlink for `btt-skr-3-ez-h723`

### What did you expect to happen

only one configuration for this board/chipset should exist.

### How to reproduce

N/A, (visible in git repo)

### Additional information

I would submit a PR to fix the regression (I'm assuming a rebase/merge from upstream or main re-introduced this at some point), but I'm thinking this could adversely affect users who chose the configuration that caused the `btt-skr-3-ez` symlink to be created. 

We'd need to update udev rules for the `btt-skr-3-ez-h723` to somehow _unlink_ the `btt-skr-3-ez`, and then there'd be the issue of what happens if a user has a config include for any of the config files in `btt-skr-3-ez`.

**Comment by miklschmidt** [comment]
Those are two different STM chips, two different versions of the board:
https://github.com/Rat-OS/RatOS-configuration/blob/v2.x/boards/btt-skr-3-ez/firmware.config#L12
vs
https://github.com/Rat-OS/RatOS-configuration/blob/v2.x/boards/btt-skr-3-ez-h723/firmware.config#L12

The default (the one that launched) was h743, hence the name with no mcu discriminating suffix. It's however specified in the name in the configurator:
https://github.com/Rat-OS/RatOS-configuration/blob/v2.x/boards/btt-skr-3-ez/board-definition.json#L3
vs
https://github.com/Rat-OS/RatOS-configuration/blob/v2.x/boards/btt-skr-3-ez-h723/board-definition.json#L3
