### ISSUE TITLE
4p fan configs point to the same pin

### ISSUE THREAD

**Issue by jhorn70** [Rat-OS/RatOS-configuration#189]
### What happened

The RatOS/4pin-fans/part-cooling-fan-25khz.cfg and RatOS/4pin-fans/toolhead-fan-25khz.cfg point to the same pin.  The toolhead should be:

pin: 4p_toolhead_cooling_pin
tachometer_pin: ^4p_toolhead_cooling_tach_pin 

Looks like the 100kHz config is correct

### What did you expect to happen

NA

### How to reproduce

NA

**Comment by miklschmidt** [comment]
Already fixed in 2.1

**Comment by miklschmidt** [comment]
2.1.0-RC1 is released. Closing.
