### ISSUE TITLE
Configuration wizard

### ISSUE THREAD

**Issue by IridianZore** [Rat-OS/RatOS-configuration#190]
### What happened

You can see on the picture. I have this major problem of clicking the button status update it Won’t go further.
And I will not get any update about the status of the board. Do you have any of this problem or no way to solve it?
![7aa193af-18d5-4c30-b24b-9227a78a0cf3](https://github.com/Rat-OS/RatOS-configuration/assets/145200529/16674c0f-598a-4e87-853e-4ed2c4a17f40)

### What did you expect to happen

Regularly I should step forward in the configuration to

### How to reproduce

I tried several times and I have still the same issue. It doesn’t matter if I change the browser.

**Comment by miklschmidt** [comment]
Please click the manual DFU button, it's much more reliable than sd card flashing. For support questions like these, please use the ratos-support channel on the discord server.
