### ISSUE TITLE
MAX31865 Option

### ISSUE THREAD

**Issue by aardvarkglory** [Rat-OS/RatOS-configuration#263]
### Is your feature request related to a problem? Please describe

No problem but would streamline configuration for those using PT100 or PT1000 and the MAX31865 chip on toolheads or printer boards.

### Describe the solution you'd like

To see an option for the MAX31865 in the Hotend Thermistor menu in the configurator.  If this is not possible, an option for "none" in the menu would be great so that the MAX31865 can be added manually without any previous config for the Hotend Thermistor.

![Screenshot 2024-06-02 081035](https://github.com/Rat-OS/RatOS-configuration/assets/3628650/f49107a8-57c9-4d45-8ccb-3e16be0611a8)

### Additional information

This would be mostly helpful on the toolheads.  If anything, implementing this for the toolheads would be helpful as adding this for every printer board might be a more tedious task and not necessary.

**Comment by miklschmidt** [comment]
I don't have plans for supporting MAX31865 for 2 reasons. 
1) A PT1000 connected to a thermistor port using a 2200 pullup (most toolboards have this option) is plenty accurate for 3d printing purposes. 
2) MAX31685 and 2 pin probes is a finicky setup, that will throw errors if the wiring (an unknown variable) adds too much resistance, etc etc.

You can always configure it in printer.cfg afterwards. Closing for now. It may be relevant sometime in 3.0, but not at this point, bigger fish to fry.
