### ISSUE TITLE
klipper-mcu-update.sh & (any) make-and-flash-mcu.sh has root/non-root requirement collision

### ISSUE THREAD

**Issue by kmarty** [Rat-OS/RatOS-configuration#29]
Hi,
in ~/klipper_config/config/scriptsklipper-mcu-update.sh is:
```
if [ "$EUID" -eq 0 ]
  then echo "ERROR: This script should not be run as root"
  exit
fi
```

and this script calls scripts "make-and-flash-mcu.sh".
But any "make-and-flash-mcu.sh" has:
```
if [ "$EUID" -ne 0 ]
  then echo "ERROR: Please run as root"
  exit
fi
```

Until Schrödingers "root" will be discovered, this can't be fullfiled.

**Comment by miklschmidt** [comment]
Thank you! Was fixed in Rat-OS/RatOS-configuration@00a03ee41ea7ca291cd4654a0c28311d4bc5a7e4
