### ISSUE TITLE
Detachable Probe Crashing

### ISSUE THREAD

**Issue by charkear** [Rat-OS/RatOS-configuration#299]
### What happened

When starting a print the detachable probe is being driven into the bed during the preheat steps.  

### What did you expect to happen

I am not using a beacon probe. There should be no beacon heat soak step.  

### How to reproduce

My v-core 400 3.1 is configured with a rapido-uhf hotend and a klicky detachable probe.   Prior to a recent software update I had no issue with z-offset.  After a software update I noticed significant first layer height issues and inconsistent z-offset repeatability.  After close observation of the begin print steps I noticed that the klicky probe is being driven into the bed causing the mounting arm and toolhead to move knocking z calibration off.  

### Additional information

I belive the macro [gcode_macro _START_PRINT_BEFORE_HEATING_BED] in file is the cause
https://github.com/Rat-OS/RatOS-configuration/blob/v2.1.x/macros.cfg 

The recent commit has disabled check for if beacon probe is configured.
https://github.com/Rat-OS/RatOS-configuration/commit/b2940394f738998b7c83e29f13364db2ea369240

10:10 AM
RatOS: Heating bed...
10:10 AM
RatOS: Heat soaking beacon...
10:10 AM
RatOS: Pre-heating extruder...
10:10 AM
Probe batch mode enabled: not stowing
10:10 AM
probe: open
10:10 AM
probe: TRIGGERED
10:10 AM
Deploying probe
10:10 AM
RatOS: Homing Z
10:10 AM
RatOS: Homing X Y Z 
10:10 AM
Probe batch mode enabled
10:10 AM
RatOS: First print coordinates X:91.793 Y:132.785
10:10 AM
File selected

**Comment by HelgeKeck** [comment]
please update ratos, should be fixed now
