### ISSUE TITLE
The pins for the part cooling fan and hotend fans are swapped

### ISSUE THREAD

**Issue by kevinkga** [Rat-OS/RatOS-configuration#34]
In my setup for the BTT Octopus Pro 446 board, I have found that the the pins for the fans don't match the diagram. 

I guess this could be fixed by generating a new diagram (https://github.com/Rat-OS/RatOS-configuration/blob/master/boards/btt-octopus-pro-446/v-core-3-wiring.png) or updating the pin mappings?

**Comment by kevinkga** [comment]
This following PR should be able to fix this on the pin mappings https://github.com/Rat-OS/RatOS-configuration/pull/35

**Comment by miklschmidt** [comment]
Hi this was a bug in the wiring diagram and is fixed :)
