### ISSUE TITLE
Make the RatOS macros handle V Core 3 enclosure

### ISSUE THREAD

**Issue by rkaronde** [Rat-OS/RatOS-configuration#38]
The defaults in the RatOS macros are great for VCore 3 without an enclosure. 
Ex. The default park while heating is in the back.

But accessing the back (Y>300) is hard with the enclosure, even when it is open.

So it would be great to have an overall variable to indicate that an enclosure is installed and then the macros could have different defaults that work better with the enclosure.

**Comment by miklschmidt** [comment]
You can use the macro variables to have it park in the front instead, see: https://os.ratrig.com/docs/configuration/macros
