### ISSUE TITLE
Compile Firmware Permission denied

### ISSUE THREAD

**Issue by hliebscher** [Rat-OS/RatOS-configuration#41]
18:40:56
echo: Firmware binaries compiled successfully! You can find them in the firmware_binaries folder in the machine tab!
18:40:56
Command {compile_binaries} finished
18:40:56
cp: cannot create regular file '/home/pi/klipper_config/firmware_binaries/firmware-btt-octopus-pro-446.bin': Permission denied

if you delete the firmware files before than it works...

**Comment by miklschmidt** [comment]
Thank you, this will be fixed in the next image release 👍
