### ISSUE TITLE
Issue with Sensorless Homing on new config

### ISSUE THREAD

**Issue by Anon0ne** [Rat-OS/RatOS-configuration#55]
I updated my configurations, and after doing so my machine failed to home. I was doing screenshots for a review I am writing; but I realized that no matter which way I modified your new script it would not home.

The first axis will home, and then the second one will not even attempt. It will then immediately try to go to half of the max distance, and home the Z axis which results in crashing etc. I reverted to the old configuration and my system will home once again.

**Comment by asierralozano** [comment]
+1 here. It is happening on the VCore3 sensorless homing config.

**Comment by miklschmidt** [comment]
This is because the current sensorless homing template is optimized for the Minion. You're gonna need to adjust your currents before homing Y on the V-Core 3. I do not recommend sensorless homing on a CoreXY, there are only downsides compared to endstops. It's not worth it.
