### ISSUE TITLE
Make the left bed screw the base screw for screw tilt adjust

### ISSUE THREAD

**Issue by HelgeKeck** [Rat-OS/RatOS-configuration#56]
the left bed screw is difficult to reach, the two right ones are much easier to access

to make the screw tilt adjust easier and more accessible please make the left screw the base screw

hail rat rig

**Comment by HelgeKeck** [comment]
also,

after screw calculating, it would be cool if the head could move to a higher parking position, followed by a m84

the user needs to remove build plate to work on the screws, thats difficult if the head is at x10

**Comment by miklschmidt** [comment]
Done! Can i have you test it out?

Screws fixed in: https://github.com/Rat-OS/RatOS-configuration/commit/30bed175a6e1f35d5ddd9b2219aef2c784975dde
