### ISSUE TITLE
Toolboard adxl naming conflict with mainboard.

### ISSUE THREAD

**Issue by Spotigus** [Rat-OS/RatOS-configuration#79]
Toolboard's adxl is the same name as mainboard's.

My fix was to change [adxl345] to [adxl345 toolboard] in the ebb's config file.

If acceptable change, ill edit all files and create pull request.

**Comment by miklschmidt** [comment]
That is actually on purpose (not a conflict, it's an override). The assumption is that with a toolboard you'd rather use that then wire one up to your board. For dual accelerometer setups like on the Minion, the Pi is already used for Y, so it all makes sense. What's your use case for having both your toolboard's accelerometer and an accelerometer connected to the main control board?

**Comment by Spotigus** [comment]
Makes sense to me. I had just chosen to only use usb to the pi.
