### ISSUE TITLE
Dangerous behaviour with stowable Probes when having a fault while Homing

### ISSUE THREAD

**Issue by Heisenberg19x** [Rat-OS/RatOS-configuration#97]
When having a fault in the process of Homing with stowable Probes the Z-Axes get's set to a homed status before it actually is homed and therefor when an error occurs in that process is afterwards on homed status in a random height

**Comment by miklschmidt** [comment]
fixed in https://github.com/Rat-OS/RatOS-configuration/commit/7c645a43b96c83671577663c83de5fac3d35cafb
